constituency_to_district = {
    # Srikakulam district
    'Ichchapuram': 'Srikakulam',
    'Palasa': 'Srikakulam',
    'Tekkali': 'Srikakulam',
    'Pathapatnam': 'Srikakulam',
    'Srikakulam': 'Srikakulam',
    'Amadalavalasa': 'Srikakulam',
    'Etcherla': 'Srikakulam',
    'Narasannapeta': 'Srikakulam',
    'Rajam (SC)': 'Vizianagaram',
    'Palakonda (ST)': 'Parvathipuram Manyam',
    'Kurupam': 'Parvathipuram Manyam',
    'Parvathipuram': 'Parvathipuram Manyam',
    'Salur': 'Parvathipuram Manyam',
    # Vizianagaram district
    'Bobbili': 'Vizianagaram',
    'Cheepurupalli': 'Vizianagaram',
    'Gajapathinagaram': 'Vizianagaram',
    'Nellimarla': 'Vizianagaram',
    'Vizianagaram': 'Vizianagaram',
    'Srungavarapukota': 'Visakhapatnam',
    # Visakhapatnam district
    'Bhimli': 'Visakhapatnam',
    'Visakhapatnam East': 'Visakhapatnam',
    'Visakhapatnam South': 'Visakhapatnam',
    'Visakhapatnam North': 'Visakhapatnam',
    'Visakhapatnam West': 'Visakhapatnam',
    'Gajuwaka': 'Visakhapatnam',
    # Anakapalli district
    'Chodavaram': 'Anakapalli',
    'V.Madugula': 'Anakapalli',
    'Araku valley': 'Alluri Sitharama Raju',
    'Paderu': 'Alluri Sitharama Raju',
    'Anakapalli': 'Anakapalli',
    'Pendurthi': 'Anakapalli',
    'ELAMANCHILI': 'Anakapalli',
    'PAYAKARAOPETA': 'Anakapalli',
    'Narsipatnam': 'Anakapalli',
    'Tuni': 'Kakinada',
    'Prathipadu': 'Kakinada',
    'Pithapuram': 'Kakinada',
    'Kakinada Rural': 'Kakinada',
    'Peddapuram': 'Kakinada',
    'Anaparthy': 'East Godavari',
    'Kakinada City': 'Kakinada',
    # Konaseema district
    'Ramachandrapuram': 'Konaseema',
    'Mummidivaram': 'Konaseema',
    'Amalapuram': 'Konaseema',
    'Razole': 'Konaseema',
    'Gannavaram': 'Konaseema',  # constituency (not to confuse with Krishna district)
    'Kothapeta': 'Konaseema',
    'Mandapeta': 'Konaseema',
    # East Godavari
    'Rajanagaram': 'East Godavari',
    'Rajahmundry City': 'East Godavari',
    'Rajahmundry Rural': 'East Godavari',
    'Jaggampeta': 'Kakinada',
    'Kovvur': 'East Godavari',
    'Nidadavole': 'East Godavari',
    # West Godavari
    'Achanta': 'West Godavari',
    'Palacole': 'West Godavari',
    'Narasapuram': 'West Godavari',
    'Bhimavaram': 'West Godavari',
    'Undi': 'West Godavari',
    'Tanuku': 'West Godavari',
    'Tadepalligudem': 'West Godavari',
    # Eluru district
    'Unguturu': 'Eluru',
    'Denduluru': 'Eluru',
    'Eluru': 'Eluru',
    'Gopalapuram': 'East Godavari',
    'Polavaram': 'Eluru',
    'Chintalapudi': 'Eluru',
    'Tiruvuru': 'NTR',
    'Nuzvid': 'Eluru',
    'Gudivada': 'Krishna',
    'Kaikalur': 'Eluru',
    'Pedana': 'Krishna',
    'Machilipatnam': 'Krishna',
    'Avanigadda': 'Krishna',
    'Pamarru': 'Krishna',
    'Penamaluru': 'Krishna',
    # NTR district
    'Vijaywada West': 'NTR',
    'Vijayawada central': 'NTR',
    'Vijayawada East': 'NTR',
    'Mylavaram': 'NTR',
    'Nandigama': 'NTR',
    'Jaggayyapeta': 'NTR',
    # Palnadu & Guntur
    'Pedakurapadu': 'Palnadu',
    'Tadikonda (SC)': 'Guntur',
    'Mangalagiri': 'Guntur',
    'Ponnur': 'Guntur',
    'Vemuru (SC)': 'Bapatla',
    'Repalle': 'Bapatla',
    'Tenali': 'Guntur',
    'Bapatla': 'Bapatla',
    'Prathipadu (SC)': 'Guntur',
    'Guntur West': 'Guntur',
    'Guntur East': 'Guntur',
    'Chilakaluripet': 'Palnadu',
    'Narasaraopet': 'Palnadu',
    'Sattenapalli': 'Palnadu',
    'Vinukonda': 'Palnadu',
    'Gurazala': 'Palnadu',
    'Macherla': 'Palnadu',
    'Yerragondapalem': 'Prakasam',
    'Darsi': 'Prakasam',
    'Parchur': 'Bapatla',
    'Addanki': 'Bapatla',
    'Chirala': 'Bapatla',
    'Santhanuthalapadu': 'Prakasam',
    'Ongole': 'Prakasam',
    'Kandukur': 'Nellore',
    'Kondapi': 'Prakasam',
    'Markapuram': 'Prakasam',
    'Giddalur': 'Prakasam',
    'Kanigiri': 'Prakasam',
    # Nellore & Tirupati regions
    'Kavali': 'Nellore',
    'Atmakur': 'Nellore',
    'Nellore City': 'Nellore',
    'Nellore Rural': 'Nellore',
    'Sarvepalli': 'Tirupati',
    'Gudur': 'Tirupati',
    'Sullurpeta': 'Tirupati',
    'Venkatagiri': 'Tirupati',
    'Udayagiri': 'Nellore',
    'Badvel': 'Kadapa',
    'Rajampet': 'Annamayya',
    'Kadapa': 'Kadapa',
    'Kodur': 'Annamayya',
    'Rayachoti': 'Annamayya',
    'Pulivendla': 'Kadapa',
    'Kamalapuram': 'Kadapa',
    'Jammalamadugu': 'Kadapa',
    'Proddatur': 'Kadapa',
    'Mydukur': 'Kadapa',
    'Allagadda': 'Nandyal',
    'Srisailam': 'Nandyal',
    'Nandikotkur': 'Nandyal',
    'Kurnool': 'Kurnool',
    'Panyam': 'Nandyal',
    'Nandyal': 'Nandyal',
    'Banaganapalle': 'Nandyal',
    'Dhone': 'Nandyal',
    'Pattikonda': 'Kurnool',
    'Kodumur': 'Kurnool',
    'Yemmiganur': 'Kurnool',
    'Mantralayam': 'Kurnool',
    'Adoni': 'Kurnool',
    'Alur': 'Kurnool',
    'Rayadurg': 'Anantapuramu',
    'Uravakonda': 'Anantapuramu',
    'Guntakal': 'Anantapuramu',
    'Tadipatri': 'Anantapuramu',
    'Singanamala': 'Anantapuramu',
    'Anantapur urban': 'Anantapuramu',
    'KALYANDURG': 'Anantapuramu',
    'Raptadu': 'Anantapuramu',
    'Madakasira': 'Sri Sathya Sai',
    'Hindupur': 'Sri Sathya Sai',
    'Penukonda': 'Sri Sathya Sai',
    'Puttaparthi': 'Sri Sathya Sai',
    'Dharmavaram': 'Sridhaysaa? No, Sri Sathya Sai',
    'Kadiri': 'Sri Sathya Sai',
    'Thamballapalle': 'Annamayya',
    'Pileru': 'Annamayya',
    'Madanapalle': 'Annamayya',
    'Punganur': 'Chittoor',
    'Chandragiri': 'Chittoor',
    'Tirupati': 'Tirupati',
    'Srikalahasti': 'Tirupati',
    'Satyavedu': 'Tirupati',
    'Nagari': 'Chittoor',
    'Gangadhara Nellore': 'Chittoor',
    'Chittoor': 'Chittoor',
    'Puthalapattu': 'Chittoor',
    'Palamaner': 'Chittoor',
    'Kuppam': 'Chittoor',
    'Rajamundry Rural': 'East Godavari',
    'Rampachodavaram': 'Alluri Sitharama Raju',
    'TANUKU': 'West Godavari',
    'Kovur': 'Nellore'
}